name: CI-CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: label-production

    env:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      database__user: ${{ secrets.database__user }}
      database__password: ${{ secrets.database__password }}
      database__name: ${{ secrets.database__name }}
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@v4

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_database__user: ${{ secrets.database__user }}
          envkey_database__password: ${{ secrets.database__password }}
          envkey_database__host: postgres
          envkey_database__name: ${{ secrets.database__name }}
          envkey_database__port: 5432

          directory: src

      - name: Check if Traefik is running and start it if needed
        run: |
          if [ "$(docker ps -q -f name=tochka_api-traefik)" ]; then
            echo "Traefik is already running."
          else
            echo "Starting Traefik..."
            docker compose -p tochka_api up --detach traefik
          fi

      - name: Check if Postgres is running and start it if needed
        run: |
          if [ "$(docker ps -q -f name=tochka_api-postgres)" ]; then
            echo "Postgres is already running."
          else
            echo "Starting Postgres..."
            docker compose -p tochka_api up --detach postgres
          fi

      - name: Build and Run Docker Compose
        run: docker compose -p tochka_api up --build --detach api
